x-base-image:   &base-image   gitlab.ika.rwth-aachen.de:5050/automated-driving/docker/ros2:rolling
x-devel-image:  &devel-image  gitlab.ika.rwth-aachen.de:5050/gkueppers/lanelet2_route_planning:latest-dev
x-run-image:    &run-image    gitlab.ika.rwth-aachen.de:5050/gkueppers/lanelet2_route_planning:latest
x-command:      &command      ros2 run lanelet2_route_planning global_planner_node

# ==============================================================================

x-build: &build
  dockerfile: ./docker/docker-ros/Dockerfile
  context: ../
  args:
    BASE_IMAGE: *base-image
    COMMAND: *command
    GIT_HTTPS_USER: $GIT_HTTPS_USER
    GIT_HTTPS_PASSWORD: $GIT_HTTPS_PASSWORD

services:
  devel:
    image: *devel-image
    build:
      target: development
      <<: *build
  run:
    image: *run-image
    build:
      target: run
      <<: *build
