/**/*:
  ros__parameters:
    ll2_map_server_name: ll2_map_server
    publish_frequency: 10.0
    action_feedback_frequency: 1.0
    sampling_distance: 1.0
    project_destination_to_reference_line: true
    destination_distance_threshold: 1.0
    enrich_route_ahead_ego_distance: 100.0
    enrich_route_behind_ego_distance: 10.0
    route_undershoot_distance: 0.0
    route_overshoot_distance: 0.0
    max_drivable_space_radius: 50.0

    # --- plan_route_action_client ---
    # waypoints:
    #   - "<LATITUDE>, <LONGITUDE>"
    enable_random_destination: false
    enable_continuous_planning: false
    cancel_route: false