services:

  lanelet2-route-planning:
    image: ghcr.io/openads-project/lanelet2_route_planning:v1.0.2
    environment:
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
    command: |
      ros2 launch lanelet2_route_planning lanelet2_route_planning_launch.py
        namespace:=/planning

  lanelet2-map-server:
    image: ghcr.io/openads-project/lanelet2_map_server:v1.1.1
    environment:
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
    command: |
      ros2 launch lanelet2_map_server lanelet2_map_server_launch.py
        namespace:=/localization
    volumes:
      - ./lanelet2_map_server/params.yml:/docker-ros/ws/install/lanelet2_map_server/share/lanelet2_map_server/config/params.yml
      - ./lanelet2_map_server/maps:/data/maps

  ego-data-publisher:
    image: ghcr.io/openads-project/lanelet2_route_planning:demo-monitoring
    environment:
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
    command: |
      ros2 topic pub -r 10
        /planning/lanelet2_route_planning/ego_data
        perception_msgs/msg/EgoData
        "{header: {frame_id: 'map'}, state: {model_id: 1, continuous_state: [80.0, 90.0, 0.75, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.5708, 0.0, 0.0, 0.0]}, length: 4.0, width: 1.8, height: 1.5}"

  tf-publisher:
    image: ghcr.io/openads-project/lanelet2_route_planning:demo-monitoring
    environment:
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
    command: |
      ros2 run tf2_ros static_transform_publisher
        --frame-id map
        --child-frame-id base_link
        --x 80.0 --y 90.0 --z 0.0
        --roll 0.0 --pitch 0.0 --yaw 1.5708

  rviz:
    image: ghcr.io/openads-project/lanelet2_route_planning:demo-monitoring
    environment:
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      DISPLAY: ${DISPLAY}
    command: rviz2 -d /config.rviz
    volumes:
      - ./rviz/config.rviz:/config.rviz
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
