float64 target_pos_x                    # Destination x in map coordinates
float64 target_pos_y                    # Destination y in map coordinates
---
bool destination_reached                # Flag indicating if the destination was reached
builtin_interfaces/Time duration        # Duration of the maneuver
---
std_msgs/Header header
float64 destination_x                   # Map x of destination
float64 destination_y                   # Map y of destination
int64 current_lanelet                   # ID of lanelet vehicle is currently on
builtin_interfaces/Time route_timestamp # Timestamp of the referred route msg
int64[] path_remaining_ll_ids           # IDs of the current and next LLs of the ego vehicle along the shortest path